%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clear all
tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'NK1_loop';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('NK1_loop.log');
M_.exo_names = 'e_A';
M_.exo_names_tex = 'e\_A';
M_.exo_names_long = 'e_A';
M_.endo_names = 'k';
M_.endo_names_tex = 'k';
M_.endo_names_long = 'k';
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'R');
M_.endo_names_tex = char(M_.endo_names_tex, 'R');
M_.endo_names_long = char(M_.endo_names_long, 'R');
M_.endo_names = char(M_.endo_names, 'Infl');
M_.endo_names_tex = char(M_.endo_names_tex, 'Infl');
M_.endo_names_long = char(M_.endo_names_long, 'Infl');
M_.endo_names = char(M_.endo_names, 'X');
M_.endo_names_tex = char(M_.endo_names_tex, 'X');
M_.endo_names_long = char(M_.endo_names_long, 'X');
M_.endo_names = char(M_.endo_names, 'L');
M_.endo_names_tex = char(M_.endo_names_tex, 'L');
M_.endo_names_long = char(M_.endo_names_long, 'L');
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'rk');
M_.endo_names_long = char(M_.endo_names_long, 'rk');
M_.endo_names = char(M_.endo_names, 'A');
M_.endo_names_tex = char(M_.endo_names_tex, 'A');
M_.endo_names_long = char(M_.endo_names_long, 'A');
M_.endo_names = char(M_.endo_names, 'Y');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y');
M_.endo_names_long = char(M_.endo_names_long, 'Y');
M_.param_names = 'k_st';
M_.param_names_tex = 'k\_st';
M_.param_names_long = 'k_st';
M_.param_names = char(M_.param_names, 'L_st');
M_.param_names_tex = char(M_.param_names_tex, 'L\_st');
M_.param_names_long = char(M_.param_names_long, 'L_st');
M_.param_names = char(M_.param_names, 'c_st');
M_.param_names_tex = char(M_.param_names_tex, 'c\_st');
M_.param_names_long = char(M_.param_names_long, 'c_st');
M_.param_names = char(M_.param_names, 'w_st');
M_.param_names_tex = char(M_.param_names_tex, 'w\_st');
M_.param_names_long = char(M_.param_names_long, 'w_st');
M_.param_names = char(M_.param_names, 'R_st');
M_.param_names_tex = char(M_.param_names_tex, 'R\_st');
M_.param_names_long = char(M_.param_names_long, 'R_st');
M_.param_names = char(M_.param_names, 'rk_st');
M_.param_names_tex = char(M_.param_names_tex, 'rk\_st');
M_.param_names_long = char(M_.param_names_long, 'rk_st');
M_.param_names = char(M_.param_names, 'X_st');
M_.param_names_tex = char(M_.param_names_tex, 'X\_st');
M_.param_names_long = char(M_.param_names_long, 'X_st');
M_.param_names = char(M_.param_names, 'beta');
M_.param_names_tex = char(M_.param_names_tex, 'beta');
M_.param_names_long = char(M_.param_names_long, 'beta');
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, 'alpha');
M_.param_names_long = char(M_.param_names_long, 'alpha');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'theta');
M_.param_names_tex = char(M_.param_names_tex, 'theta');
M_.param_names_long = char(M_.param_names_long, 'theta');
M_.param_names = char(M_.param_names, 'epsilon');
M_.param_names_tex = char(M_.param_names_tex, 'epsilon');
M_.param_names_long = char(M_.param_names_long, 'epsilon');
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, 'eta');
M_.param_names_long = char(M_.param_names_long, 'eta');
M_.param_names = char(M_.param_names, 'rho');
M_.param_names_tex = char(M_.param_names_tex, 'rho');
M_.param_names_long = char(M_.param_names_long, 'rho');
M_.param_names = char(M_.param_names, 'r_Infl');
M_.param_names_tex = char(M_.param_names_tex, 'r\_Infl');
M_.param_names_long = char(M_.param_names_long, 'r_Infl');
M_.param_names = char(M_.param_names, 'r_R');
M_.param_names_tex = char(M_.param_names_tex, 'r\_R');
M_.param_names_long = char(M_.param_names_long, 'r_R');
M_.exo_det_nbr = 0;
M_.exo_nbr = 1;
M_.endo_nbr = 10;
M_.param_nbr = 16;
M_.orig_endo_nbr = 10;
M_.aux_vars = [];
M_.Sigma_e = zeros(1, 1);
M_.Correlation_matrix = eye(1, 1);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('NK1_loop_static');
erase_compiled_function('NK1_loop_dynamic');
M_.lead_lag_incidence = [
 1 3 0;
 0 4 0;
 0 5 0;
 0 6 13;
 0 7 0;
 0 8 0;
 0 9 14;
 0 10 0;
 2 11 0;
 0 12 0;]';
M_.nstatic = 6;
M_.nfwrd   = 2;
M_.npred   = 2;
M_.nboth   = 0;
M_.nsfwrd   = 2;
M_.nspred   = 2;
M_.ndynamic   = 4;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:1];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(10, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(1, 1);
M_.params = NaN(16, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 37;
M_.NNZDerivatives(2) = -1;
M_.NNZDerivatives(3) = -1;
load rPi_Int;
load rR_Int;
M_.params( 15 ) = rPi_Int(1);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(1);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK1 oo_ M_;
M_.params( 15 ) = rPi_Int(2);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(2);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK2 oo_ M_;
M_.params( 15 ) = rPi_Int(3);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(3);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK3 oo_ M_;
M_.params( 15 ) = rPi_Int(4);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(4);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK4 oo_ M_;
M_.params( 15 ) = rPi_Int(5);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(5);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK5 oo_ M_;
M_.params( 15 ) = rPi_Int(6);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(6);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK6 oo_ M_;
M_.params( 15 ) = rPi_Int(7);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(7);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK7 oo_ M_;
M_.params( 15 ) = rPi_Int(8);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(8);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK8 oo_ M_;
M_.params( 15 ) = rPi_Int(9);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(9);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK9 oo_ M_;
M_.params( 15 ) = rPi_Int(10);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(10);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK10 oo_ M_;
M_.params( 15 ) = rPi_Int(11);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(11);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK11 oo_ M_;
M_.params( 15 ) = rPi_Int(12);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(12);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK12 oo_ M_;
M_.params( 15 ) = rPi_Int(13);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(13);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK13 oo_ M_;
M_.params( 15 ) = rPi_Int(14);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(14);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK14 oo_ M_;
M_.params( 15 ) = rPi_Int(15);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(15);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK15 oo_ M_;
M_.params( 15 ) = rPi_Int(16);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(16);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK16 oo_ M_;
M_.params( 15 ) = rPi_Int(17);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(17);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK17 oo_ M_;
M_.params( 15 ) = rPi_Int(18);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(18);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK18 oo_ M_;
M_.params( 15 ) = rPi_Int(19);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(19);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK19 oo_ M_;
M_.params( 15 ) = rPi_Int(20);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(20);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK20 oo_ M_;
M_.params( 15 ) = rPi_Int(21);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(21);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK21 oo_ M_;
M_.params( 15 ) = rPi_Int(22);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(22);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK22 oo_ M_;
M_.params( 15 ) = rPi_Int(23);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(23);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK23 oo_ M_;
M_.params( 15 ) = rPi_Int(24);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(24);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK24 oo_ M_;
M_.params( 15 ) = rPi_Int(25);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(25);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK25 oo_ M_;
M_.params( 15 ) = rPi_Int(26);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(26);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK26 oo_ M_;
M_.params( 15 ) = rPi_Int(27);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(27);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK27 oo_ M_;
M_.params( 15 ) = rPi_Int(28);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(28);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK28 oo_ M_;
M_.params( 15 ) = rPi_Int(29);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(29);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK29 oo_ M_;
M_.params( 15 ) = rPi_Int(30);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(30);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK30 oo_ M_;
M_.params( 15 ) = rPi_Int(31);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(31);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK31 oo_ M_;
M_.params( 15 ) = rPi_Int(32);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(32);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK32 oo_ M_;
M_.params( 15 ) = rPi_Int(33);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(33);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK33 oo_ M_;
M_.params( 15 ) = rPi_Int(34);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(34);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK34 oo_ M_;
M_.params( 15 ) = rPi_Int(35);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(35);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK35 oo_ M_;
M_.params( 15 ) = rPi_Int(36);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(36);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK36 oo_ M_;
M_.params( 15 ) = rPi_Int(37);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(37);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK37 oo_ M_;
M_.params( 15 ) = rPi_Int(38);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(38);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK38 oo_ M_;
M_.params( 15 ) = rPi_Int(39);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(39);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK39 oo_ M_;
M_.params( 15 ) = rPi_Int(40);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(40);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK40 oo_ M_;
M_.params( 15 ) = rPi_Int(41);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(41);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK41 oo_ M_;
M_.params( 15 ) = rPi_Int(42);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(42);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK42 oo_ M_;
M_.params( 15 ) = rPi_Int(43);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(43);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK43 oo_ M_;
M_.params( 15 ) = rPi_Int(44);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(44);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK44 oo_ M_;
M_.params( 15 ) = rPi_Int(45);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(45);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK45 oo_ M_;
M_.params( 15 ) = rPi_Int(46);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(46);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK46 oo_ M_;
M_.params( 15 ) = rPi_Int(47);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(47);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK47 oo_ M_;
M_.params( 15 ) = rPi_Int(48);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(48);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK48 oo_ M_;
M_.params( 15 ) = rPi_Int(49);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(49);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK49 oo_ M_;
M_.params( 15 ) = rPi_Int(50);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(50);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK50 oo_ M_;
M_.params( 15 ) = rPi_Int(51);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(51);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK51 oo_ M_;
M_.params( 15 ) = rPi_Int(52);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(52);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK52 oo_ M_;
M_.params( 15 ) = rPi_Int(53);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(53);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK53 oo_ M_;
M_.params( 15 ) = rPi_Int(54);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(54);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK54 oo_ M_;
M_.params( 15 ) = rPi_Int(55);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(55);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK55 oo_ M_;
M_.params( 15 ) = rPi_Int(56);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(56);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK56 oo_ M_;
M_.params( 15 ) = rPi_Int(57);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(57);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK57 oo_ M_;
M_.params( 15 ) = rPi_Int(58);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(58);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK58 oo_ M_;
M_.params( 15 ) = rPi_Int(59);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(59);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK59 oo_ M_;
M_.params( 15 ) = rPi_Int(60);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(60);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK60 oo_ M_;
M_.params( 15 ) = rPi_Int(61);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(61);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK61 oo_ M_;
M_.params( 15 ) = rPi_Int(62);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(62);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK62 oo_ M_;
M_.params( 15 ) = rPi_Int(63);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(63);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK63 oo_ M_;
M_.params( 15 ) = rPi_Int(64);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(64);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK64 oo_ M_;
M_.params( 15 ) = rPi_Int(65);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(65);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK65 oo_ M_;
M_.params( 15 ) = rPi_Int(66);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(66);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK66 oo_ M_;
M_.params( 15 ) = rPi_Int(67);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(67);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK67 oo_ M_;
M_.params( 15 ) = rPi_Int(68);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(68);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK68 oo_ M_;
M_.params( 15 ) = rPi_Int(69);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(69);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK69 oo_ M_;
M_.params( 15 ) = rPi_Int(70);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(70);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK70 oo_ M_;
M_.params( 15 ) = rPi_Int(71);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(71);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK71 oo_ M_;
M_.params( 15 ) = rPi_Int(72);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(72);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK72 oo_ M_;
M_.params( 15 ) = rPi_Int(73);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(73);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK73 oo_ M_;
M_.params( 15 ) = rPi_Int(74);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(74);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK74 oo_ M_;
M_.params( 15 ) = rPi_Int(75);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(75);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK75 oo_ M_;
M_.params( 15 ) = rPi_Int(76);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(76);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK76 oo_ M_;
M_.params( 15 ) = rPi_Int(77);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(77);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK77 oo_ M_;
M_.params( 15 ) = rPi_Int(78);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(78);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK78 oo_ M_;
M_.params( 15 ) = rPi_Int(79);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(79);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK79 oo_ M_;
M_.params( 15 ) = rPi_Int(80);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(80);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK80 oo_ M_;
M_.params( 15 ) = rPi_Int(81);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(81);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK81 oo_ M_;
M_.params( 15 ) = rPi_Int(82);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(82);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK82 oo_ M_;
M_.params( 15 ) = rPi_Int(83);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(83);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK83 oo_ M_;
M_.params( 15 ) = rPi_Int(84);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(84);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK84 oo_ M_;
M_.params( 15 ) = rPi_Int(85);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(85);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK85 oo_ M_;
M_.params( 15 ) = rPi_Int(86);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(86);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK86 oo_ M_;
M_.params( 15 ) = rPi_Int(87);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(87);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK87 oo_ M_;
M_.params( 15 ) = rPi_Int(88);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(88);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK88 oo_ M_;
M_.params( 15 ) = rPi_Int(89);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(89);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK89 oo_ M_;
M_.params( 15 ) = rPi_Int(90);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(90);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK90 oo_ M_;
M_.params( 15 ) = rPi_Int(91);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(91);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK91 oo_ M_;
M_.params( 15 ) = rPi_Int(92);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(92);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK92 oo_ M_;
M_.params( 15 ) = rPi_Int(93);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(93);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK93 oo_ M_;
M_.params( 15 ) = rPi_Int(94);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(94);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK94 oo_ M_;
M_.params( 15 ) = rPi_Int(95);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(95);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK95 oo_ M_;
M_.params( 15 ) = rPi_Int(96);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(96);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK96 oo_ M_;
M_.params( 15 ) = rPi_Int(97);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(97);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK97 oo_ M_;
M_.params( 15 ) = rPi_Int(98);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(98);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK98 oo_ M_;
M_.params( 15 ) = rPi_Int(99);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(99);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK99 oo_ M_;
M_.params( 15 ) = rPi_Int(100);
r_Infl = M_.params( 15 );
M_.params( 16 ) = rR_Int(100);
r_R = M_.params( 16 );
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
save results_NK100 oo_ M_;
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.01)^2;
resid(1);
steady;
oo_.dr.eigval = check(M_,options_,oo_);
options_.irf = 0;
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
conditional_variance_decomposition=0;
save('NK1_loop_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('NK1_loop_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('NK1_loop_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('NK1_loop_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('NK1_loop_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
